apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptodash
  namespace: crypto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cryptodash
  template:
    metadata:
      labels:
        app: cryptodash
    spec:
      containers:
        - name: cryptodash
          image: ghcr.io/cl-krma/cryptodash-app:df2a4966744782e16efba053dd5896910042d6f7

          ports:
            - containerPort: 3000
          env:
            - name: SITE_TITLE
              value: "Infra Prog Crypto"
---
apiVersion: v1
kind: Service
metadata:
  name: cryptodash-service
  namespace: crypto
spec:
  selector:
    app: cryptodash
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
